# Generated by Django 5.2.7 on 2025-11-01 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretchatcontact',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='secretchatcontact',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='secretchatcontact',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='secretchatcontact',
            name='user',
        ),
        migrations.AddField(
            model_name='secretchatcontact',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
