# Generated by Django 5.2.7 on 2025-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0003_remove_secretchatcontact_contact_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RenameField(
            model_name='secretmessage',
            old_name='receiver',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='secretmessage',
            old_name='sender',
            new_name='sender_user',
        ),
        migrations.AddField(
            model_name='secretchatcontact',
            name='username',
            field=models.CharField(default='Guest', max_length=150),
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='receiver_name',
            field=models.CharField(default='Guest', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='sender_name',
            field=models.CharField(default='Guest', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretchatcontact',
            name='contact_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='secretchatcontact',
            unique_together={('username', 'contact_username')},
        ),
    ]
