# Generated by Django 5.2.7 on 2025-11-01 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0004_alter_secretmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='permissionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Permission Request', 'verbose_name_plural': 'Permission Requests'},
        ),
        migrations.AlterModelOptions(
            name='secretchatcontact',
            options={'verbose_name': 'Secret Chat Contact', 'verbose_name_plural': 'Secret Chat Contacts'},
        ),
        migrations.AlterModelOptions(
            name='secretmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Secret Message', 'verbose_name_plural': 'Secret Messages'},
        ),
        migrations.AddField(
            model_name='secretmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
