# Generated by Django 5.2.7 on 2025-11-01 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0006_alter_notification_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='secretchatcontact',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='secretchatcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretchatcontact',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='receiver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_local_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secretmessage',
            name='sender_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_local_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
