# Generated by Django 5.2.7 on 2025-11-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0008_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
