# Generated by Django 5.2.7 on 2025-11-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0010_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
